### ISSUE TITLE
Modify font color

### ISSUE THREAD

**Issue by liuxiao6110** [BlueGreenMagick/Edit-Field-During-Review-Cloze#100]
Hello, thank you very much for designing the addon. I have some questions during the use process. I can modify my content during review, such as adding new words or bold fonts, but I cannot use the shortcut keys to change the font color. May I ask how to handle this.

**Comment by liuxiao6110** [comment]
Version ⁨2.1.64 (581f82c5)⁩
Python 3.9.15 Qt 6.4.3 PyQt 6.4.0

**Comment by BlueGreenMagick** [comment]
In the add-on config, in `Formatting` tab, check if `fontcolor` is checked. During review, Ctrl+click the text to turn on edit mode, then select the text and press the shortcut fot `fontcolor`. (default is F7)
