### ISSUE TITLE
Bug report: undo shortcut does not work

### ISSUE THREAD

**Issue by xxhk-org** [BlueGreenMagick/Edit-Field-During-Review-Cloze#101]
The below checklist isn't manditory, but suggested before creating an issue.
- [ ] I've updated this add-on to the latest version
- [ ] I've tried disabling all other add-ons except this one.

**Describe the bug**

When using the plugin, notes in review often flashed by before I had a chance to look at them and then reappeared, and the undo shortcut Ctrl+Z didn't work, so combining the two I'm guessing that the plugin automatically triggers the undo shortcut.

I'm using the latest version of Anki for the Windows platform, and the plugin is up to date as well!

**To Reproduce**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Debug Info**
In the toolbar, go to `Help > About...`. In the About window, click the `Copy Debug Info` button at the bottom beside an 'OK' button. Please paste the contents below.

**Comment by BlueGreenMagick** [comment]
I can't think off the top of my head why this would occur. Can you check if this doesn't occur when you disable the add-on?

**Comment by xxhk-org** [comment]
> I can't think off the top of my head why this would occur. can you check if this doesn't occur when you disable the add-on?

Yes, when I disabled the plugin and restarted Anki, the undo shortcut Ctrl+Z came right back!

**Comment by xxhk-org** [comment]
> I can't think off the top of my head why this would occur. can you check if this doesn't occur when you disable the add-on?

The issue with flashing has been resolved through the official forums, and was indeed an issue with the software itself  https://forums.ankiweb.net/t/anki-2-1-66-beta/32463/11?u=xxhk . The issue with the shortcut key conflict with the undo function has also been resolved by updating the plugin. Thanks!
