### ISSUE TITLE
Incompatible with Anki 23.10 beta1 - Windows - Qt6

### ISSUE THREAD

**Issue by liuxiao6110** [BlueGreenMagick/Edit-Field-During-Review-Cloze#104]
Could you please try to make the plugin compatible with the Anki 23.10 beta1 - Windows - Qt6 version? This version updated the FSRS, which is important to me.

**Comment by khonkhortisan** [comment]
this gets it to load, but make every field in every note type editable→save button does nothing
```py
from anki.utils import point_version
ankiver_minor = point_version()#int(ankiversion.split(".")[2])
```

**Comment by BlueGreenMagick** [comment]
Fixed! Thanks for all the details!
