### ISSUE TITLE
How to assign more than one keyboard shortcut for different font colors?

### ISSUE THREAD

**Issue by yfjuu6** [BlueGreenMagick/Edit-Field-During-Review-Cloze#105]
I've known how to assign a keybord shortcut to change font color during review from this :
[[Modify font color · Issue #100 · BlueGreenMagick/Edit-Field-During-Review-Cloze (github.com)](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/issues/100)]
I'd like to assign more than one keyboard shortcut for different font colors to switch between them by keyboard shortcuts during review e.g. :
F7(red) || F8(blue) etc ...
I found this Add-on : [Quick Colour Changing](https://ankiweb.net/shared/info/2491935955)
 It does what I want but in the "main add window" and the "Edit current window", Not during review.
Any idea to do that Please !

**Comment by BlueGreenMagick** [comment]
https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/blob/master/FAQ.md#can-i-have-multiple-formatting-shortcuts

So something like this: 
```json
  "special_formatting": {
    "fontcolor": {
      "enabled": true,
      "command": "foreColor",
      "shortcut": "F7",
      "arg": {
        "type": "color",
        "value": "#00f"
      }
    },
    "fontcolor": {
      "enabled": true,
      "command": "foreColor",
      "shortcut": "F8",
      "arg": {
        "type": "color",
        "value": "#0f0"
      }
    },
```
