### ISSUE TITLE
Cannot set certain fields to be editable

### ISSUE THREAD

**Issue by Ghaithdev** [BlueGreenMagick/Edit-Field-During-Review-Cloze#106]
The below checklist isn't manditory, but suggested before creating an issue.
-I've updated this add-on to the latest version. Downloaded yesterday so should be latest version
-I've tried disabling all other add-ons except this one. (Doing so did not change the issue)

**Describe the bug**
I use a field on some cards to determine if the card is a "sound card" ie if the audio should be presented first or the written sentence. This field doesn't appear on the card but is instead used to edit the layout of the card, I guess that this is why it doesn't appear for editting in the config options but wanted to confirm

**To Reproduce**
1. Go to the config page for the addon
2. Click on fields tab
3. Select card type "Arabic with optional sound"
4. The Field "sound toggle" doesn't appear on the list of fields that edits can be allowed on

**Screenshots**
Fields available on the card:
![image](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/assets/140157218/618ce943-4d49-4964-9a2d-4e163bf4e69b)
Formatting of the card:
![image](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/assets/140157218/30ba1408-1e04-416b-b222-0101e60c3fc6)
Toggle edit screen:
![image](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/assets/140157218/6ad0e42d-ed34-4197-8f2c-27c16267d858)
**Debug Info**
In the toolbar, go to `Help > About...`. In the About window, click the `Copy Debug Info` button at the bottom beside an 'OK' button.     
    Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
    Platform: Windows-10-10.0.22621
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-10-08 08:18:36
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Edit Field During Review Cloze ['385888438', 2023-07-31T14:21, '6.15', mod]
    PassFail 2 Remove the Easy and Hard buttons ['876946123', 2023-01-24T01:59, 'None', '']
    RefoldEase ['819023663', 2023-02-22T11:27, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    385888438 819023663 876946123
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by BlueGreenMagick** [comment]
You are correct. It's because the field `{{Toggle Sound}}` doesn't appear on card. The field needs to be shown on the card to be edited after all!
