### ISSUE TITLE
After editing a card and reviewing it, Undo Review does not return me to the card.

### ISSUE THREAD

**Issue by tmujir** [BlueGreenMagick/Edit-Field-During-Review-Cloze#107]
The below checklist isn't manditory, but suggested before creating an issue.
- [Yes] I've updated this add-on to the latest version
- [Yes] I've tried disabling all other add-ons except this one.

**Describe the bug**
What is the bug, and what behaviour did you expect instead?
BUG: After editing a card and answering the card, if I press Ctrl+Z to "Undo Review", I don't revert to the card. 
 
**To Reproduce**
1. Show a card, flip the card, select Normal/Easy etc. 
2. Press Ctrl+Z which should bring you back to the card.
3. Now edit the card, flip it, select Normal/Easy etc.
4. Now press Ctrl+Z, it undoes your answer, but it doesn't bring you back to the original card. 

Thanks for your hard work on this add-on which is absolutely best in class.

**Comment by BlueGreenMagick** [comment]
Thanks for the report! 

It looks like something changed in the latest Anki update. The error doesn't occur up to v2.1.64, but appears on v23.10(beta3)

**Comment by BlueGreenMagick** [comment]
Can I ask what Anki version you are using?

**Comment by tmujir** [comment]
Sorry for the late response

Version ⁨2.1.66 (70506aeb)⁩
Python 3.9.15 Qt 6.5.2 PyQt 6.5.2

**Comment by tmujir** [comment]
Hello and Happy New Year! I am not familiar with coding, just wanted to inquire when this bug might be fixed? Thank you!

**Comment by tmujir** [comment]
Just wanted to say thank you so much for fixing this, it genuinely makes my life so much better even years later
