### ISSUE TITLE
Subscript hotkey adds equal sign?

### ISSUE THREAD

**Issue by zer0xs** [BlueGreenMagick/Edit-Field-During-Review-Cloze#11]
After enabling subscript in the config, I can't activate it without equal sign being generated using CTRL + =

![subscript](https://user-images.githubusercontent.com/50467871/75907035-7ee06b80-5dfc-11ea-8fb4-3d12ca413861.gif)

Just really annoying. Thanks!

**Comment by BlueGreenMagick** [comment]
Sorry for the bug! I believe I found the issue and I'll try to upload a fix soon.

**Comment by BlueGreenMagick** [comment]
Updating the addon should fix the issue now!
