### ISSUE TITLE
The plugin does not work properly in version 23.10.beat6 qt6.

### ISSUE THREAD

**Issue by liuxiao6110** [BlueGreenMagick/Edit-Field-During-Review-Cloze#110]
Hello,

I would like to report an issue with the plugin. It doesn't work properly in version 23.10.beat6 qt6. Whenever I try to copy and paste some content, it gives me the following error:

Error: An error occurred while running. Please start Anki while holding down the Shift key to temporarily disable plugin loading. If the error only occurs when certain plugins are enabled, please go to "Tools" > "Add-ons," disable some plugins, and restart Anki. Repeat these steps to identify the plugin causing the error and report it to the plugin author. Debug info: Anki 23.10 (72e57456) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2 Platform: Windows-10-10.0.19041 Flags: frz=True ao=True sv=3 Add-ons, last update check: 2023-10-29 10:25:04 Related add-on: Edit Field During Review Cloze

Caught exception: Traceback (most recent call last): File "aqt.webview", line 46, in cmd File "aqt.webview", line 153, in _onCmd File "aqt.webview", line 660, in _onBridgeCmd File "_aqt.hooks", line 5407, in __call__ File "C:\Users\11111\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 175, in handle_pycmd_message mime = mw.app.clipboard().mimeData(mode=QClipboard.Clipboard) AttributeError: type object 'QClipboard' has no attribute 'Clipboard'

Furthermore, even after reporting the error, I can still "edit" cards. However, these edits are not saved, and when I review the card again, the previously edited content is not displayed.

Please fix this issue as soon as possible! This plugin has greatly improved my efficiency in using Anki and has been an invaluable tool for my studies. Thank you very much!

**Comment by BlueGreenMagick** [comment]
fixed!
