### ISSUE TITLE
After pressing ctrl, text inside the first span moves slightly to the left.

### ISSUE THREAD

**Issue by BurrowBird** [BlueGreenMagick/Edit-Field-During-Review-Cloze#117]
- [x] I've updated this add-on to the latest version
- [x] I've tried disabling all other add-ons except this one.

**Describe the bug**
After pressing ctrl, text moves slightly to the left. I expect it to not do that.

**To Reproduce**
1. Set html tag to span
2. Press ctrl
3. Text shifts a few pixels to the left

**Comment by BurrowBird** [comment]
Actually this sounds like what is described here:
_https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/issues/66#issuecomment-974844007_

The text only moves in the reviewer, not in the editor/preview.

**Comment by BlueGreenMagick** [comment]
I'm unable to reproduce this on Anki v24.04. Can you post your note type HTML and CSS, and your Anki version?

**Comment by BurrowBird** [comment]
Anki 23.12.1
[html.txt](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/files/14913711/html.txt)
[css.txt](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/files/14913712/css.txt)

Updating to Anki 24.04 fixed the issue.
