### ISSUE TITLE
Feature request: change shortcuts

### ISSUE THREAD

**Issue by aPaci95** [BlueGreenMagick/Edit-Field-During-Review-Cloze#12]
Hello, your addon is great! I wanted to aske  if it could be possible to add the option to customize shortcuts. For example i changed the editor F7 in Alt+X and i would like to have the same shortcut if i edit while i review through your fantastic addon!. It would be really appreciated

**Comment by BlueGreenMagick** [comment]
This feature was added with v6.0!
