### ISSUE TITLE
Adding a horizontal line <hr>

### ISSUE THREAD

**Issue by DerIshmaelite** [BlueGreenMagick/Edit-Field-During-Review-Cloze#123]
I hope for a way to add horizontal lines with your addon :)

**Comment by BlueGreenMagick** [comment]
It's not documented anywhere, but you can actually achieve this by following below steps:

1. Open the add-on config, click 'advanced'.
2. Paste the following section into the advanced config, to line just after `"special_formatting": {`.
```json
"insertHR": {
    "arg": {
        "type": "text",
        "value": "<hr>"
    },
    "command": "insertHTML",
    "enabled": true,
    "shortcut": "Ctrl + -"
},
```


So after pasting, the config should look like this: (you can ignore the leading whitespaces each line)

```json
...
"special_formatting": {
    "insertHR": {
        "arg": {
            "type": "text",
            "value": "<hr>"
        },
        "command": "insertHTML",
        "enabled": true,
        "shortcut": "Ctrl + -"
    },
    "fontcolor": {
...
```
