### ISSUE TITLE
Edit while in "Preview"

### ISSUE THREAD

**Issue by Zechmmaster** [BlueGreenMagick/Edit-Field-During-Review-Cloze#124]
There is already a request for this but it was like 3 years ago and I don't think there's been any updates yet. Basically, is it possible to edit cards in preview mode, like the guy does here: 
![image](https://github.com/user-attachments/assets/be3f8be8-24da-4d13-ba3e-14a47c97a487)
Thank you!

**Comment by BlueGreenMagick** [comment]
Added!
