### ISSUE TITLE
Idea: Render empty cards (cloze type) in the reviewer 

### ISSUE THREAD

**Issue by BaekToDaFuture** [BlueGreenMagick/Edit-Field-During-Review-Cloze#14]
Hello. 
First of all thank you for sharing your add-on.

I have an idea that could potentially work synergistically with this add-on.

If **empty** cloze cards could be rendered in the reviewer (instead of the usual message about 'this card is empty'), one could flip through the added cards in the reviewer and add clozes as needed.

My main thought is that, sometimes when adding cloze cards, it's a hassle and time consuming to add clozes in the editor after writing out the card.
If this could be implemented into this, or a separate add-on, one could rapidly enter cards after another without manually adding clozes, *and then* add them as one reads through the added cards.

What do you think?

**Comment by BlueGreenMagick** [comment]
This should be  #12

**Comment by BlueGreenMagick** [comment]
To be honest, I can't really see any time advantage making clozes in the reviewer than in the editor. But I think #12 feature could address this at the same time. I'll put it on my todo list, but no idea when I'll go about trying to implement it.

**Comment by BaekToDaFuture** [comment]
Okay. No problem.
