### ISSUE TITLE
Disable Pop-Up Dictionary while editing

### ISSUE THREAD

**Issue by NicolasCuri** [BlueGreenMagick/Edit-Field-During-Review-Cloze#17]
Hey! First and foremost, I cannot thank you enough for creating this add-on. I love everything you've done, and I very much appreciate all your contributions to our community.

I was going to ask if it's possible to create an option to disable the Pop-up mechanism while editing the cards. This is because very often now, when I select a word to either bold, delete, or whatever, it triggers the pop-up dictionary add-on, and it kinda lags. Thanks for considering!

**Comment by BlueGreenMagick** [comment]
Thank you for your kind words :) As for popup dictionary, I'd love that feature as well! I was already going to work on it, but forgot about it for a while. I'll get back on it soon.

**Comment by BlueGreenMagick** [comment]
Should be fixed! Double click shouldn't work anymore. Use the shortcut instead.
