### ISSUE TITLE
Changing the super/subscipt shortcuts

### ISSUE THREAD

**Issue by silentcicada1** [BlueGreenMagick/Edit-Field-During-Review-Cloze#18]
Awesome add on that I use everyday. Can't image anki without it. I like the idea of using super/sub scripts but the shortcut "ctrl + =" and "ctrl + shift + =" interferes with the zoom add on shortcut. Is it possible to either have an option to edit the shortcuts ourselves or get them changed to "alt + =" and "alt + shift + =".

**Comment by BlueGreenMagick** [comment]
You can now customize shortcuts! You mya need to update Anki to v2.1.41+ to use the newer add-on version.
