### ISSUE TITLE
When resizing images in review picture shrinks

### ISSUE THREAD

**Issue by silentcicada1** [BlueGreenMagick/Edit-Field-During-Review-Cloze#20]
When you click on the field to edit the picture the picture shrinks outside of the border. It makes it harder to determine exactly how the picture will look when resized due to this function. Otherwise I'm super impressed with how you've integrated this new function into your already incredible add on. Thank you!

https://drive.google.com/open?id=1Y_illzvVLyIdvIhHYJ3rtm6XBr66XuB1

**Comment by BlueGreenMagick** [comment]
Sorry for the bug! To understand what is going on here, could you give me the html source of the field? (Find the card in browser, click on the field that has the image, press `ctrl + shift + x`)

**Comment by zer0xs** [comment]
I have the same issue. Here is code from one of my cards. I even disabled the original image resize extension. `Test<div><br></div><div><img class="" src="31E19CC1-46E6-4C67-AB81-A69B67A43917.jpg" style="width: 380px; height: 507px;"><br></div>`

**Comment by BlueGreenMagick** [comment]
The issue was fixed in the update. Thanks for the bug reports!
