### ISSUE TITLE
Wont let me resize in browser or edit menu

### ISSUE THREAD

**Issue by DoctorToBeIn23** [BlueGreenMagick/Edit-Field-During-Review-Cloze#24]
Since the most recent update ^ Title...

**Comment by Arthur-Milchior** [comment]
I believe you didn't but the bug report in the good git repo. This add-on is not related at all to browser/edit. I believe you want to make the bug report on https://github.com/Arthur-Milchior/anki-resize-image

**Comment by DoctorToBeIn23** [comment]
I thought you sent the code to this add o and they are now merged?

**Comment by Arthur-Milchior** [comment]
No. This add-on deal with reviewer. My add-on still deal with the editor. Those are two different add-ons, even if some code are commons

**Comment by BlueGreenMagick** [comment]
This addon only lets you resize images in reviewer. To resize in note editor, please use this other [addon ](https://ankiweb.net/shared/info/1103084694)by Arthur instead.
