### ISSUE TITLE
fixing anki mobile issue

### ISSUE THREAD

**Issue by doulovetrees** [BlueGreenMagick/Edit-Field-During-Review-Cloze#25]
since i use anki on mobile, i followed the directions on the add on page that says to paste this in the template
<div class="ondesktop">{{edit:cloze:FieldName}}</div>
<div class="onmobile">{{cloze:FieldName}}</div>

I changed field name to edit:cloze:Text since Front Side doesn't work.

But now the front card, the question is shown twice. Not sure why.

![Annotation 2020-03-29 163348](https://user-images.githubusercontent.com/62851909/77860073-1c03a980-71db-11ea-88d6-1a1d3efad357.jpg)

**Comment by BlueGreenMagick** [comment]
Hello did you add 
```
.mobile .ondesktop {  display:none;  }
.android .ondesktop{  display:none;  }
.win .onmobile{  display:none;  }
.mac .onmobile{  display:none;  }
.linux .onmobile{  display:none;  }
```
to Styling?

**Comment by doulovetrees** [comment]
yes i did! but i noticed that when i delete the {{edit:cloze:Text}}, it doesn't show up twice. is it ok to delete this?

**Comment by BlueGreenMagick** [comment]
Oh yeah! You are supposed to write
 ```
<div class="ondesktop">{{edit:cloze:Front}}</div>
<div class="onmobile">{{cloze:Front}}</div>
``` 
instead of {{edit:cloze:Front}}

**Comment by doulovetrees** [comment]
oops sorry one last thing! do i need to add that code to the Back card as well?

**Comment by BlueGreenMagick** [comment]
I'm actually not quite sure because I don't have an iphone. I don't even know if the issue is still there or it got fixed. You should just use whatever you want and change it if you see an error message on AnkiMobile.
