### ISSUE TITLE
Title on empty fields on pressing Ctrl

### ISSUE THREAD

**Issue by Cupbox** [BlueGreenMagick/Edit-Field-During-Review-Cloze#27]
Hi. I usually have multiple empty fields in my card. And I use your addon to edit most of them. The issues arises when their empty. Pressing Ctrl (I use the button to activate mode) would expand the editable fields like so
![2020-05-26_21-07-58](https://user-images.githubusercontent.com/13769570/82923870-12908680-9f6b-11ea-99c0-03203291a280.gif)
With many fields it is hard to tell which field you are editing. Therefore it would be convenient if upon pressing control, the name of the editable field appeared as well like so
![uploadxe12](https://user-images.githubusercontent.com/13769570/82924221-8fbbfb80-9f6b-11ea-87f3-2d273a0d0f8f.png)
As an addendum as demonstrated in the gif, it is hard to select another editing field while pressing Ctrl. You have to release and then select the other one.
Thank you.

**Comment by BlueGreenMagick** [comment]
Added in the latest update!

**Comment by Cupbox** [comment]
Thanks alot!
