### ISSUE TITLE
empty field in-place editing?

### ISSUE THREAD

**Issue by Laern2Do** [BlueGreenMagick/Edit-Field-During-Review-Cloze#29]
hi, i like this add-on thank you for releasing it,

is it possible to assess empty fields while reviewing to edit? i don't know if this feature is available or I'm just derping, thx!

(I ctrl+click everywhere but only field with text allow me to edit XD)

v2.1.22, window10

**Comment by DoctorToBeIn23** [comment]
I know this was supposed to be in this update, do we need to add any code to our cards or config the add on? I really appreciate you adding this feature I requested. If it helps I am on a mac and Command = control... 

Version 2.1.25 (898801eb)
PS: I also updated the add on this morning and restarted it

**Comment by BlueGreenMagick** [comment]
If the field is merely empty, it should be editable.

But if you are using a conditional replacement in your note type (i.e. {{#FieldName}} {{/FieldName}} ), then I'm afraid you cannot with this addon. Anki skips over what is inside the conditional replacement entirely if the field is empty, and this addon cannot know what is inside it. 

So you have to edit your note type and remove conditional replacement to edit empty fields.

**Comment by Laern2Do** [comment]
yeep that was the problem, thx you! taking away conditional placement allow for empty-field in place editing
