### ISSUE TITLE
Incompatible with GODMODE Cloze

### ISSUE THREAD

**Issue by mytestingsolution** [BlueGreenMagick/Edit-Field-During-Review-Cloze#40]
Thank you for the great add on!

I noticed that "edit field during review" isn't compatible with "Godmode cloze" (https://ankiweb.net/shared/info/1508677152) which creates two different shortcuts 1) increases the cloze # by one and 2) which continues the same cloze number, thus if you're going to create multiple clozes on the same level (like continuing c1::) you don't have to go back and edit the cloze.

I've disabled all other add-ons and that didn't change anything. I contacted the other plugins' add on and he thought the issue was on [line 220](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/blob/5b48455267ceb67886c070792beccccfc1d3dc77/edit_field_during_review_cloze/web/global_card.js) 

Unfortunately, I don't have the programming ability to make the changes but the other author's add on suggested: "one way might be to combine the code from the two add-ons; then rewrite the Cloze shortcuts in the Edit Field add-on to be what they are in the Godmode add-on, so they don't conflict."

Thank you for any insights.

**Comment by BlueGreenMagick** [comment]
I'm guessing it's this issue: https://github.com/Joseph-Y/godmode/issues/3

To clarify, the shortcuts don't work in editor (Either in add cards window, or in Browse)? Or is this a feature request to add godmode's functionality to this addon, so what godmode does will also work when editing while reviewing?

**Comment by mytestingsolution** [comment]
Yes, that's correct. The god mode shortcuts don't work while editing in the review, but as I was re-reading through the details of your add on, I realized that you do support Ctrl+Shift+Alt+C, so I think this is a moot point. I have been using Godmode cloze for a while and didn't realize this functionality had been more broadly adopted.

Thank you take the time to respond. I think this issue is resolved. Really appreciate your contributions to Anki!

**Comment by BlueGreenMagick** [comment]
Ctrl+Shift+Alt+C is a built-in Anki shortcut actually.
