### ISSUE TITLE
addon breaking the answer side of the cards

### ISSUE THREAD

**Issue by bjcmd2024** [BlueGreenMagick/Edit-Field-During-Review-Cloze#42]
For some reason, after installing this addon the flip side of my card is just giving me a long stream of errors. I am on Anki 2.1.33

**Comment by BlueGreenMagick** [comment]
Can you copy paste the error log? It's not possible to figure out what the problem is without it.

**Comment by bjcmd2024** [comment]
<img width="613" alt="Screen Shot 2021-02-20 at 10 34 39 AM" src="https://user-images.githubusercontent.com/79379154/108630873-f51a1b80-741b-11eb-864c-204cee1af336.png">

**Comment by BlueGreenMagick** [comment]
It's probably because of a conflict between this and another addon. The Redesign and Anki-TouchScreen addon is known to be incompatible. Or it may be another addon.
