### ISSUE TITLE
can't use the pop up dictionary beta add on while using the edit field addon 

### ISSUE THREAD

**Issue by greenjamez** [BlueGreenMagick/Edit-Field-During-Review-Cloze#43]
whenever I try to double click a word to show in pop dictionary it only allow me to edit the field so any help with that? thanks.

**Comment by BlueGreenMagick** [comment]
You can go to the addon config and set `ctrl_click` to `true`. It will only let you edit the field by `ctrl+click` on the field, so double click will trigger the pop up dictionary.

**Comment by greenjamez** [comment]
Thanks for your reply
Really appreciate your work.
