### ISSUE TITLE
Typing apostrophe ' will enter in my edits

### ISSUE THREAD

**Issue by D4n22** [BlueGreenMagick/Edit-Field-During-Review-Cloze#44]
Please help!!!

When I'm editing during the review, if I type an apostrophe (i.e. ') then its accepting the review prematurely and going back to the regular card with any edits I made up to the apostrophe. This occurs even with all other addon's disabled. I'm using the Anking card type which requires clicking a button to access the field. (https://drive.google.com/drive/folders/1hc44GX3vVfiEHIz1mChZhghA_DBK4dlS)

For example, if I try to write "I don't know" it would be truncated as "I don" because the edits got cut short

It's really annoying when I have speed focus mode on because then the edits get submitted and then speedfocus changes to the next card so I have to go back. During regular editing I have no issues with putting an apostrophe. It's only during editing with reviews that the edit gets submitted. 

If I click and open one of the special field (e.g. Pathoma), type in an edit with an apostrophe (which gets cancelled) and then press Pathoma again I can type an apostrophe. If I then repeat this one more time or I press tab after editing, the next time I can't use apostrophes.

Occasionally if I only type an apostrophe first it gives me this error  (which I think means nothing was typed):

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-11 07:21:54

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-28>", line 2, in _linkHandler
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt\editor.py", line 421, in mungeHTML
  File "aqt\gui_hooks.py", line 1606, in __call__
  File "aqt\editor.py", line 1217, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'

**Comment by BlueGreenMagick** [comment]
I think you are using an outdated version of the addon. Can you try again after updating the addon and see if the bug's still there?

**Comment by D4n22** [comment]
Thanks for the response, I tried updating and I'm still having the same issue, surprised that no one else is having it too

**Comment by BlueGreenMagick** [comment]
Sorry, but I'm unable to reproduce this bug. 

Here is the steps I've taken to try to reproduce it:
1. I've downloaded and used the basic-ankingmed note type which I assumed you are using.
2. Edited the note type template to make pathoma hidden field and the front/back field to be editable
3. In the reviewer, tried editing fields (including pathoma one) to be `I'm having`, just plain `'`, etc.

And it worked fine to me, so I can't figure out what the difference between our configuration is.

One more thing - could you check that you can go to this addon's page by clicking "View add-on page"? You could be running a manually downloaded version in which case you can't update.

**Comment by D4n22** [comment]
Awesome, I'm so impressed that you figured it out!! What does that mean on my end then, and what should I do for it to be fixed?
