### ISSUE TITLE
Edit Field During Review (Cloze)- when I typ "edit" in card types it is shrinking the size of the letter

### ISSUE THREAD

**Issue by ankidoc** [BlueGreenMagick/Edit-Field-During-Review-Cloze#46]
like I said. How can I "restore" the size or select a bigger lettersize? I actually have to clue about coding. thanks in advanced!

![Bildschirmfoto 2021-03-28 um 15 05 39](https://user-images.githubusercontent.com/81517565/112753288-4e570b00-8fd7-11eb-86d9-9e8fc44a4d68.jpg)

**Comment by ankidoc** [comment]
sry! solved it myself! stupid me :)

**Comment by BlueGreenMagick** [comment]
Glad you fixed it! :)
