### ISSUE TITLE
Doesn't work with symbols as you type 

### ISSUE THREAD

**Issue by aPaci95** [BlueGreenMagick/Edit-Field-During-Review-Cloze#48]
Symbols as you type doesn't work in the field editor during the reviews in Anki 2.1.43. The editor works correctly, but the keywords don't convert in symbols. Symbols as you type works perfectly in the editor though.
It doesn't give any error, it just doesn't convert the keywords in symbols!
It's no big deal, as 2.1.43 is super-recent and you can still use the editor, so it's not a problem, i just wanted to let you know ! 
Have a nice day!

I also submitted the issue in the other addon github: https://github.com/jefdongus/insert-symbols-anki-addon/issues/27

**Comment by BlueGreenMagick** [comment]
Won't fix.

The goal of this add-on is not to make the Reviewer into Editor, but to be able to edit in the Reviewer. So add-ons that target the Editor will not work in the Reviewer even with this add-on.
