### ISSUE TITLE
Way to edit during preview?

### ISSUE THREAD

**Issue by MicaHorton** [BlueGreenMagick/Edit-Field-During-Review-Cloze#51]
Hi, 
I was wondering if it's possible to be able to edit a card from the preview browser (like shown in the screenshot.) I use the preview browser for practicing math problems and keep track of how many times I've done the problem in a field instead of using Anki's review algorithm because (in my experience) I don't think it works well with long problems that take pen and paper to do. Currently, I can edit the number, but it won't save and will revert to the original once I close the preview window.

![Screen Shot 2021-05-20 at 2 01 30 PM](https://user-images.githubusercontent.com/38822211/119048342-f522ac80-b973-11eb-86d5-36ff5a30603e.png)

**Comment by RabbleRousy** [comment]
Came here to ask for the same. Seems to be a feature missing on Mac only, as in [this video](https://youtu.be/OJxndUGN8Cg?t=430) you can see him editing a card from the preview window :/
Would be really cool if this was also added for MacOS, as it is extremely important for this workflow ^^

**Comment by Zechmmaster** [comment]
I thought he was on Mac though?
Also has anyone found a solution for it? (I'm on Windows and also have this problem)

**Comment by BlueGreenMagick** [comment]
Added! Please update the add-on and it should work.

As a side note, I'm not sure what's with the youtube either. I don't think this add-on ever supported editing in the previewer.
