### ISSUE TITLE
Not functioning after 6/21 update

### ISSUE THREAD

**Issue by gracegong1** [BlueGreenMagick/Edit-Field-During-Review-Cloze#52]
I'm on the newest version of Anki and the newest version of the add-on, and its not working when I click on the text :(

**Comment by KR673** [comment]
I found that the Add-on has added new Settings, You can try it with `ctrl + click`, and this can be changed on the Add-on's configration page.

**Comment by BlueGreenMagick** [comment]
Unfortunately, if you've never opened addon config before, the old config value doesn't transfer to the updated version. So for those users, single click to edit the cards have changed to `ctrl + click`.
