### ISSUE TITLE
An error after pressing playback sound button

### ISSUE THREAD

**Issue by George843** [BlueGreenMagick/Edit-Field-During-Review-Cloze#53]
The below checklist isn't manditory, but suggested before creating an issue.
- [YES] I've updated this add-on to the latest version
- [YES] I've tried disabling all other add-ons except this one.

**Describe the bug**
What is the bug, and what behaviour did you expect instead?
- When I push the play button pop up an error message and disappear sound file from Anki

**To Reproduce**
1. Go to 'any card with play button'
2. Click on the 'play button'
3. Scroll down to unnecessary

**Screenshots**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-05 22:06:17

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 36, in cmd
  File "aqt\webview.py", line 135, in _onCmd
  File "aqt\webview.py", line 580, in _onBridgeCmd
  File "aqt\reviewer.py", line 349, in _linkHandler
  File "aqt\sound.py", line 859, in play_clicked_audio
IndexError: list index out of range

**Debug Info**
In the toolbar, go to `Help > About...`. In the About window, click the `Copy Debug Info` button at the bottom beside an 'OK' button. Please paste the contents below.
    
    Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-07-05 22:06:17
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Edit Field During Review Cloze ['385888438', 2021-06-25T07:33, '6.4', mod]
    
    ===IDs of active AnkiWeb add-ons===
    385888438
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2020-07-29T23:37, 'None', '']
    Advanced Browser ['874215009', 2021-02-21T17:38, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-05-03T21:46, 'None', '']
    Anki Simulator ['817108664', 2021-02-21T18:44, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T03:20, 'v1.1.3', mod]
    Auto Ease Factor ['1672712021', 2021-03-21T21:11, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2021-06-18T08:21, 'None', '']
    Batch Editing ['291119185', 2019-09-19T20:04, 'None', '']
    BetterSearch ['1052724801', 2021-05-19T03:30, 'None', mod]
    Browser Resizer ['1435775540', 2020-09-08T05:04, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2021-05-27T19:47, 'None', mod]
    Copy notes ['1566928056', 2021-02-20T02:54, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2019-03-02T06:14, 'None', '']
    Extended Card Stats During Review ['1008566916', 2019-03-02T06:14, 'None', '']
    Extended Heatmap ['2011818092', 2021-06-26T21:26, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2021-05-19T03:29, 'None', mod]
    Fastbar- with nightmode support ['46611790', 2021-05-19T03:50, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2021-05-06T20:45, 'None', mod]
    Free Weekend - or Any Other Day ['742185195', 2020-04-10T14:57, 'None', mod]
    Google Translate ['1536291224', 2021-05-23T13:15, 'None', mod]
    High Yield Tags ['1918380616', 2020-06-30T23:35, 'None', mod]
    Image Editor ['307397307', 2021-06-21T02:24, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T05:21, 'None', '']
    Image Style Editor ['1593969147', 2020-12-17T16:06, 'None', mod]
    Leaderboard ['41708974', 2021-06-16T22:40, 'None', mod]
    Learning Step and Review Interval Retention ['1949865265', 2020-12-29T01:40, 'None', '']
    Media Import ['1531997860', 2018-07-14T15:32, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T12:09, 'None', mod]
    More Overview Stats 21 ['738807903', 2021-02-05T20:35, 'None', mod]
    Notion Toggles Loader ['1940767534', 2021-05-23T21:48, 'None', mod]
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T09:26, 'None', '']
    ReMemorize Rescheduler with sibling and logging v142 ['323586997', 2020-11-20T08:27, 'None', mod]
    Reset Ease Automatically ['12081346', 2021-04-16T13:02, 'None', mod]
    Reset Ease ['947935257', 2020-12-27T17:59, 'None', '']
    Resize images in editor ['1103084694', 2021-05-30T03:04, 'None', mod]
    Reverso importer ['2060267742', 2020-09-30T11:11, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T16:23, 'None', '']
    Special Fields ['1102281552', 2021-06-21T00:27, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T12:11, 'None', '']
    Straight Reward ['957961234', 2021-01-11T15:37, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-12T14:47, 'None', mod]
    The KING of Button Add-ons ['374005964', 2020-04-18T01:33, 'None', '']
    True Retention ['613684242', 2017-11-19T23:43, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2020-05-08T16:16, 'None', '']
    avgEase for Anki  2141 ['1129477042', 2021-06-27T14:58, 'None', '']
    deck and card info sidebar during review ['673114053', 2020-09-20T15:17, 'None', '']
    put ALL due learning cards first modified v2 support ['1807121582', 2019-11-24T22:20, 'None', '']
    rebuild allempty all filtered decks enhanced fork ['104518886', 2021-07-05T12:12, 'None', '']
    when is next learning card due today due ['563204849', 2020-09-13T16:51, 'None', mod]

**Comment by BlueGreenMagick** [comment]
Fixed!
