### ISSUE TITLE
Inactive Cloze-Fields 

### ISSUE THREAD

**Issue by peterkibbel** [BlueGreenMagick/Edit-Field-During-Review-Cloze#54]
Thanks for the last update. Great improvements!

Though, I cannot solve the following problem: My cards have multiple cloze-fields. Those cloze-fields not beeing asked still take up space due to the addon. Any chance to make it vanish totally, as it does without the addon?

![image](https://user-images.githubusercontent.com/80814873/126280635-209f163b-ca99-4798-9811-3acc6ea1eebd.png)

![image](https://user-images.githubusercontent.com/80814873/126280870-d098a86b-6dc3-43bb-b300-ee521b9f6008.png)

![image](https://user-images.githubusercontent.com/80814873/126280893-c5a3790d-a2a8-4b50-b182-9749b5764293.png)

I hope I explained the problem properly. If not, let me know :)

Huge thanks!

Hendrik

**Comment by BlueGreenMagick** [comment]
Can I see your note type? I don't remember any native options to hide cloze fields that aren't being asked, so I'm guessing you used some javascript to remove the field not being asked.

**Comment by peterkibbel** [comment]
I'm using the cloze-note-type.

Got some scripts, but I wouldn't know them being responsible for hiding the field not being asked.

`<script>
  // ##############  BUTTON REVEAL SHORTCUTS  ##############
  // Visit https://keycode.info/ to get the number/letter for the key you want to assign
  // The shortcuts are  Alt  +  the number/letter below
  // All shortcuts will also open with "H" if using the Hint Hotkeys add-on


  var Kontext = '75'
  var OpenCloseAll = '72'
  var ScrollToHint = true;
</script>


<script>
  function myFunction(divid, id, divid) {
    var x = document.getElementById(divid), y = document.getElementById(id), z = document.getElementById(divid);
    if (x.style.display == "none") 
    {
    x.style.display = "block"; y.style.display = "none"; z.scrollToId;
    } 
        else {
         x.style.display = "none"; y.style.display = "inline-block";
        }
    if (ScrollToHint){
        z.scrollIntoView({
         behavior: "smooth", //"auto" for instant scrolling
         block: "start",
         inline: "nearest"
    });}
    }
    document.onkeydown = function(evt) {
    evt = evt || window.event;
        if (evt.altKey && evt.keyCode == Kontext) {
            myFunction('button-Kontext', 'hint-Kontext', 'button-Kontext')}
        if (evt.altKey && evt.keyCode == nid) {
            myFunction('button-nid', 'hint-nid', 'button-nid')}
        if (evt.altKey && evt.keyCode == errata) {
            document.getElementById('button-errata').click(); document.getElementById('button-errata').style.display = "inline-block";}
        if (evt.altKey && evt.keyCode == amboss) {
            document.getElementById('button-amboss').click(); document.getElementById('button-amboss').style.display = "inline-block";}
        if (evt.altKey && evt.keyCode == zusatz) {
            myFunction('button-zusatz', 'hint-zusatz', 'button-zusatz')}
        if (evt.altKey && evt.keyCode == hammer) {
            myFunction('button-hammer', 'hint-hammer', 'button-hammer')}
        if (evt.altKey && evt.keyCode == meditricks) {
            myFunction('button-meditricks', 'hint-meditricks', 'button-meditricks')}
        if (evt.altKey && evt.keyCode == klinik) {
            myFunction('button-klinik', 'hint-klinik', 'button-klinik')}
        if (evt.altKey && evt.keyCode == image) {
            myFunction('button-img', 'hint-img', 'button-img')}
        
        if (evt.altKey && evt.keyCode == OpenCloseAll) {
        try{myFunction('button-img', 'hint-img', 'button-img')}
        finally{try{myFunction('button-klinik', 'hint-klinik', 'button-klinik')}
        finally{try{myFunction('button-meditricks', 'hint-meditricks', 'button-meditricks')}
        finally{try{myFunction('button-zusatz', 'hint-zusatz', 'button-zusatz')}
        finally{myFunction('button-hammer', 'hint-hammer', 'button-hammer')}}}}
        }
    }



  function myFunctionnoscroll(divid, id, divid) {
    var x = document.getElementById(divid), y = document.getElementById(id), z = document.getElementById(divid);
    if (x.style.display == "none") 
    {
    x.style.display = "block"; y.style.display = "none"; z.scrollToId;
  }  }


let scroll_to_cloze = () => {
   let mycloze = document.getElementsByClassName("cloze")[0];
   const element = mycloze;
   const elementRect = element.getBoundingClientRect();
   const absoluteElementTop = elementRect.top + window.pageYOffset;
   const middle = absoluteElementTop - (window.innerHeight / 2);
   window.scrollTo(0, middle);
}
if (typeof onShownHook !== "undefined") {
   //for Anki 2.1.x
   onShownHook.push(function() {
       scroll_to_cloze();
   })
} else {
   // for AnkiDroid
   setTimeout(function() {
       scroll_to_cloze();
   }, 10);
}
</script>`

**Comment by BlueGreenMagick** [comment]
I'm guessing you are using something like Cloze Overlapper. I've took a quick look at it, but I still have no idea how Cloze Overlapper manages to do what it does :shrug: 

That said, you can go to config, turn on 'Ctrl + Click', and it should be less obstructive.

**Comment by peterkibbel** [comment]
Woooouhh! Huge thanks
No, I'm not using cloze overlapper.
Anyway: "Ctrl + Click" pretty much solved the problem.
Thank you :)
