### ISSUE TITLE
Bug when rating a card after editing with the add-on.

### ISSUE THREAD

**Issue by Casartellii** [BlueGreenMagick/Edit-Field-During-Review-Cloze#56]
The below checklist isn't mandatory, but suggested before creating an issue.
- [x] I've updated this add-on to the latest version
- [x] I've tried disabling all other add-ons except this one.

**Describe the bug**
Since I update to 2.1.45 this bug appeared:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.45 (355e66e8) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-30 11:51:21

Caught exception:
Traceback (most recent call last):
  File "anki\scheduler\v2.py", line 767, in _logLrn
  File "anki\scheduler\v2.py", line 762, in log
  File "anki\cards.py", line 190, in time_taken
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 139, in _onCmd
  File "aqt\webview.py", line 592, in _onBridgeCmd
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\1046608507\main.py", line 193, in linkHandler
    return _old(self, url)
  File "aqt\reviewer.py", line 504, in _linkHandler
  File "aqt\reviewer.py", line 425, in _answerCard
  File "anki\scheduler\v2.py", line 459, in answerCard
  File "anki\scheduler\v2.py", line 485, in _answerCard
  File "anki\scheduler\v2.py", line 578, in _answerLrnCard
  File "anki\scheduler\v2.py", line 771, in _logLrn
  File "anki\scheduler\v2.py", line 762, in log
  File "anki\cards.py", line 190, in time_taken
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

**To Reproduce**

Well i think the gift explains pretty much.

**Screenshots**
![cRWVLM8L4H](https://user-images.githubusercontent.com/88219689/127726598-6f8441d9-b62b-4697-872a-14a77ed8a133.gif)

**Debug Info**
    
    Anki 2.1.45 (355e66e8) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-07-30 11:51:21
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2021-07-10T15:40, 'None', '']
    Add Table ['1237621971', 2021-07-10T14:37, 'None', mod]
    AnkiConnect ['2055492159', 2021-07-13T21:59, 'None', '']
    Asset Manager ['656021484', 2021-04-05T17:24, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2021-07-29T09:55, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2021-05-27T13:47, 'None', '']
    Button Colours Good Again ['2494384865', 2021-04-06T11:57, 'None', '']
    Closet For Anki ['272311064', 2021-04-12T11:09, 'None', '']
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-12T00:12, 'None', '']
    Collapsible Fields ['1896168623', 2021-03-07T12:08, 'None', '']
    Countdown To Events and Exams ['1143540799', 2021-03-13T17:40, 'None', '']
    Custom Styles font color background colour classes ['1899278645', 2021-03-02T21:41, 'None', '']
    Deck name in title 21 ['699175524', 2019-05-31T22:05, 'None', '']
    Edit Field During Review Cloze ['385888438', 2021-07-30T07:32, '6.5', mod]
    External Note Editor for the Browser ['1996266159', 2020-03-31T17:59, 'None', '']
    Fastbar- with nightmode support ['46611790', 2021-05-18T21:50, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2021-07-28T16:50, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T14:06, 'None', '']
    Image Editor ['307397307', 2021-06-20T20:24, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    Language Tools - Learn Foreign Languages with Anki ['771677663', 2021-07-20T06:27, 'None', mod]
    More Decks Stats and Time Left ['1556734708', 2021-01-27T06:09, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-30T16:13, 'None', '']
    Quick tagging 21 ['304770511', 2020-02-11T03:17, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T03:35, 'None', mod]
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2021-06-21T13:05, 'None', mod]
    See Previous Card Ratings in Reviewer ['1906641654', 2021-07-30T21:52, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T06:11, 'None', '']
    Straight Reward ['957961234', 2021-01-11T09:37, 'None', '']
    Symbols As You Type ['2040501954', 2021-03-21T23:17, 'None', '']
    Symbols ['1461102936', 2019-04-18T17:21, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-06T22:31, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1046608507 109531687 1103084694 1143540799 1237621971 1374772155 1436550454 1461102936 1463041493 1556734708 1781298089 1896168623 1899278645 1906641654 1933645497 1996266159 2040501954 2055492159 225180905 2494384865 272311064 304770511 307397307 318752047 385888438 46611790 656021484 699175524 738807903 771677663 831846358 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Mini Format Pack ['295889520', 2018-07-24T14:45, 'None', '']
    Minimal Theme ['867316254', 2021-07-18T09:24, 'None', '']
    Persistent Editor ['1686259334', 2021-02-11T21:05, 'None', '']
    Tag Entry Enhancements v2 ['536796161', 2020-11-10T08:28, 'None', '']
    TagSelectorV2 ['1022577188', 2020-08-13T00:09, 'None', mod]
    Ze Frozen Fields ['94610912', 2021-02-11T21:06, 'None', '']

**Comment by BlueGreenMagick** [comment]
Fixed! Sorry for the trouble!

**Comment by Casartellii** [comment]
Great support! Thanks a lot.
