### ISSUE TITLE
Cannot edit close during review

### ISSUE THREAD

**Issue by shv592** [BlueGreenMagick/Edit-Field-During-Review-Cloze#61]
Hello, 

For some reason, the code is not working for the field - TEXT. 

<div class=frontbg>
{{edit:cloze:Text}}
</div>

This does not work. It only works when I "show answer" and all the hints appear - I can edit the hints but not the Text field. Can you please help me? 

I'm using the Anking Card styling

**Comment by BlueGreenMagick** [comment]
Can you check that you have [Edit Field During Review (Cloze)](https://ankiweb.net/shared/info/385888438) installed, not [Edit Field During Review](https://ankiweb.net/shared/info/1020366288)?

**Comment by shv592** [comment]
<img width="908" alt="Screen Shot 2021-09-22 at 5 56 32 PM" src="https://user-images.githubusercontent.com/86445043/134427555-999a0af3-faa2-4d21-bdfd-01b07332059c.png">


Yes I have edit field during review (cloze)

**Comment by BlueGreenMagick** [comment]
That's weird. Could you export a note from that note type so I can debug what might be wrong with it? You can do it by going to Browse, selecting a card, then Notes > Export Notes.

**Comment by shv592** [comment]
i can't add a file here  so I've uploaded it to my google drive. 

here's the link to the exported card: https://drive.google.com/file/d/1WtSSol_m8FvFBhRtjhdkvnlDwls4xOHS/view?usp=sharing

thank you so much for your help. if you can figure this out, it would really help me!

**Comment by shv592** [comment]
since you're helping me with that, it would be great if you could also check why the Amboss add on does not pop up in the text field either ... maybe they're both related? Because both the AMBOSS add on and the edit cloze do not work in the **Text Fields** only ... there's something blocking any add-on's from working in the text field and i'm not sure why.. 

thank you so so much! :):)

**Comment by shv592** [comment]
here is the link to hte notes exported again: https://drive.google.com/file/d/1WtSSol_m8FvFBhRtjhdkvnlDwls4xOHS/view?usp=sharing


I've gotten rid of all the extra stuff from the Anking card and just left my coding for the card style...

**Comment by BlueGreenMagick** [comment]
In the styling, remove `z-index: -1` from `.frontbg { }`. That made the element go behind other elements.

**Comment by shv592** [comment]
omg! thank you so so much! what an easy fix - thank you again :) great work!
