### ISSUE TITLE
Adding an image during review (from clipboard/after I copied an image) does not work after I updated to Version ⁨2.1.48.

### ISSUE THREAD

**Issue by ccont123** [BlueGreenMagick/Edit-Field-During-Review-Cloze#63]
The below checklist isn't manditory, but suggested before creating an issue.
- [x] I've updated this add-on to the latest version
- [x] I've tried disabling all other add-ons except this one.

**Describe the bug**
What is the bug, and what behaviour did you expect instead?

**To Reproduce**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Debug Info**
In the toolbar, go to `Help > About...`. In the About window, click the `Copy Debug Info` button at the bottom beside an 'OK' button. Please paste the contents below.

**Comment by ccont123** [comment]
It either doesnt work, or it just adds the name of the image (it varies).

**Comment by ccont123** [comment]
Update: 
- screenshot -> copy image -> and paste -> nothing appears 
- use an image from my desktop -> copy and paste -> name of image

**Comment by ballin4dapandas** [comment]
similar issue - I can't paste screenshots in the editor but I used to be able to. I can only paste copied images, but when I try to use windows+shift+s and paste, nothing occurs.

**Comment by ccont123** [comment]
I was never able to solve it, but I did notice that as long as I am pasting something immediately after the text it works. 

For example, if I paste a picture after the word "girl" : 
- it will work when I paste (x) in "girl"x 
- but it will not work if paste it as "girl"_x (underscore being a space) 

Hope this helps and hopefully we can get this problem fixed!

**Comment by IMGHandover** [comment]
Adding

{{^Extra}}
<div id=extra>{{edit:Extra}}</div> 
{{/Extra}}
 
to my back template fixed it when trying to paste pictures into the extra field. Hopefully that helps figure out cause/solution.

**Comment by BlueGreenMagick** [comment]
I believe I found the issue and fixed it! The fixed version should be uploaded to AnkiWeb within this week after some testing.

**Comment by BlueGreenMagick** [comment]
The new version with the fix was uploaded
