### ISSUE TITLE
No Fields tab in addon config

### ISSUE THREAD

**Issue by palashman** [BlueGreenMagick/Edit-Field-During-Review-Cloze#68]
- [x] I've updated this add-on to the latest version 
- [x] I've tried disabling all other add-ons except this one.

**Describe the bug**
I red in manual: _«Please check if you enabled editing your field in the note type. Go to the addon config, select the Fields tab. Choose your note type from the dropdown and see if the fields are editable.»_
But I see no Fields tab here, and no dropdown, please look at screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/44644036/150285994-9610addb-7957-4d8f-bcf7-4f8820b60e9d.png)

**Comment by vinniec2** [comment]
I'm sorry, I apologise for necroposting, but I have exactly the same problem, I did not want to open another report.
The anki version is the penultimate 24.06.2 (qt 6), I don't have the tab field

![anki_note](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/assets/167593524/17a9bc17-49fc-44ce-966b-00f0c2d3b654)

**Comment by BlueGreenMagick** [comment]
Perhaps the add-on is not enabled. Can you try rerunning Anki and see if that changes anything?

If problem still persists, can you check if the add-on is running? That is, try manually editing yout note type template to use `{{edit:Field}}` instead of `{{Field}}` and see if the field becomes editable during review.

**Comment by vinniec2** [comment]
Sorry, I don't know if you are replying to me, I seem to remember that I had deleted my message because I had fixed it, I had caused the problem by not restarting anki, and so it seemed more logical to delete my message instead of distracting others.
Sorry, it must have gotten in your email anyway!
