### ISSUE TITLE
Feature request: Resize image in add-on

### ISSUE THREAD

**Issue by Arthur-Milchior** [BlueGreenMagick/Edit-Field-During-Review-Cloze#7]
Hi,

A lot of people asks me whether my add-on https://ankiweb.net/shared/info/1103084694 can be used with your add-on. This add-on allows user to click-drag to resize image.
I'm not sure how easy it would be to use my code in your add-on. I would assume that it would not be extremely hard, but my past experience show me that I'm pretty bad at guessing the number of unexpected problem that may occur. 
So, I've got two questions:

Would you accept to merge a PR which allow user to add image. This would add to the code complexity. 
Would you be interested in doing the work yourself.

As I wrote on https://www.kickstarter.com/projects/arthurmilchior/image-resizing-in-anki/ I don't expect to do the work unless users accept to pay me; mostly because I don't think I'll use this feature myself. But I thought it may be interesting to let you know about it.

**Comment by BlueGreenMagick** [comment]
I would of course accept any PR that improves the addon. However I'm hesitant to add several 10k code to the reviewer.

If your kickstarter do not meet its goal, I was considering developing such feature, but there are no definite plans.

**Comment by Arthur-Milchior** [comment]
The code is extremely small.
The biggest part of the code in only the jquery-ui css file, which I add to add to the code because I can't easily import it from anki. But even that could be reduced by taking only the css part I need.
Furthermore, one of the complexity of my code was to allow merging "resizing image" and "limiting image height in editor", which was a really popular request by user. And you won't have to deal with all of this complexity since, in the editor, you don't want to arbitrarily limit the size

**Comment by Arthur-Milchior** [comment]
I just double checked, and I realized that at some point, I added the whore jquery-ui file, instead of only the css. Yeah, the add-on was suddently uselessly big !
