### ISSUE TITLE
Editing issues in text when using the edit: tag

### ISSUE THREAD

**Issue by alansbury** [BlueGreenMagick/Edit-Field-During-Review-Cloze#70]
The below checklist isn't manditory, but suggested before creating an issue.
- [x] I've updated this add-on to the latest version
- [x] I've tried disabling all other add-ons except this one.

In the code of the cards, when i try to use quotation marks around the text of one of the "edit:" fields, they start they jump to a different line.

**Screenshots**
code (without the "edit:") and result:
![image](https://user-images.githubusercontent.com/102550464/160469706-37c904ed-b1b5-4270-bef5-ba51236c4faf.png)
![image](https://user-images.githubusercontent.com/102550464/160469767-a41a9a44-abdc-44c2-8f29-58f88b25d523.png)

same code adding the "edit:" bit and result:
![image](https://user-images.githubusercontent.com/102550464/160469900-204bc9c7-f5e1-4f32-94bc-b5951030c133.png)
![image](https://user-images.githubusercontent.com/102550464/160469935-14601f77-0bb1-4d36-91c7-2f1c3b00ddf5.png)

**Debug Info**
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-03-28 18:41:19
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Edit Field During Review Cloze ['385888438', 2022-02-22T06:35, '6.11', mod]
    
    ===IDs of active AnkiWeb add-ons===
    385888438
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-01-31T00:07, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2022-02-20T04:23, 'None', '']
    Batch Editing ['291119185', 2020-06-04T18:05, 'None', '']
    Cambridge Dictionary ['1875288089', 2021-03-04T14:43, 'None', '']
    Fastbar re-upload ['916436309', 2020-01-20T07:52, 'None', '']
    Hierarchical Tags 2 ['594329229', 2021-03-07T03:25, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T10:09, 'None', '']
    More Overview Stats ['2116130837', 2021-05-29T13:24, 'None', '']
    Pop-up Dictionary ['popup_dictionary', 2021-08-05T00:30, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    load balancer ['1417170896', 2020-08-06T01:58, 'None', '']

**Comment by BlueGreenMagick** [comment]
Try adding to note type styling
```css
div[data-efdrcfield] {
    display: inline-block;
}
```

Also, you should use `&quot;{{Context}}&quot;` instead of `"{{Context}}"`. It does seem to work somehow, but that may cause some other problems

**Comment by alansbury** [comment]
Thanks!
