### ISSUE TITLE
it separate audio button from sentence

### ISSUE THREAD

**Issue by omega3** [BlueGreenMagick/Edit-Field-During-Review-Cloze#74]
The below checklist isn't mandatory, but suggested before creating an issue.
- [x] I've updated this add-on to the latest version
- [x] I've tried disabling all other add-ons except this one.

**Describe the bug**

Before enabling add-on I had audio button and sentence in one line, like this:
https://i.imgur.com/Z1mTfsm.png
When add-on is enabled the sentence is moved to a new paragraph, like this:
https://i.imgur.com/X3yj1Co.png

I have simple template, nothing unusual:
```
<div style="line-height: 50%;"><br></div>
{{Sentence_Audio}} 
{{edit:cloze:Example_Cloze_Sentence}}<br>
<div style="line-height: 50%;"><br></div>
```

**To Reproduce**
I don't know how to reproduce. This happens automatically without any template editing, right after enabling add-on.

**Expected behavior**
Don't affect how things are displayed.

**Debug Info**

```

    Anki 2.1.51 (cf78a555) Python 3.9.10 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-05-03 11:00:55
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Edit Field During Review Cloze ['385888438', 2022-02-22T06:35, '6.11', mod]
    
    ===IDs of active AnkiWeb add-ons===
    385888438
    
```

**Comment by BlueGreenMagick** [comment]
Can you try adding the following line to the note type styling and see if it works?


```css
div[data-efdrcfield] {
    display: inline-block;
}
```

**Comment by omega3** [comment]
Yes it works now but (I am not sure if this is connected) but it affected my input width
https://i.imgur.com/6kRubnx.png
I had it full screen width before.

**Comment by BlueGreenMagick** [comment]
That's what `display: inline-block` does. It makes the field only wide as its content. Without it, the field is shown on the next line and takes up an entire line. (Which is `display: block`)

If you want `edit:type:field` to take up the whole width, but other `edit:field` to not, you can make only the `{{edit:type:field}}` be `display:block` and other non-type editable fields `display:inline-block` like the following

Template:
```html
<div class="edit-type">
  {{edit:type:cloze:field}}
</div>

{{edit:Other Field}}
{{edit: Other Field2}}
```
Styling:
```css
div[data-efdrcfield] {
    display: inline-block;
}

.edit-type div[data-efdrcfield] {
    display: block;
}
```
