### ISSUE TITLE
It doesn't display cloze field content

### ISSUE THREAD

**Issue by omega3** [BlueGreenMagick/Edit-Field-During-Review-Cloze#75]
The below checklist isn't manditory, but suggested before creating an issue.
- [x] I've updated this add-on to the latest version
- [x] I've tried disabling all other add-ons except this one.

**Describe the bug**
It doesn't display cloze field content at first
https://i.imgur.com/6kRubnx.png
only after mouse click
https://i.imgur.com/loMKxz5.png

**To Reproduce**
I don't know. Maybe it is just anki version or night mode issue. I use native anki dark theme.

**Debug Info**

  ```
  
    Anki 2.1.51 (cf78a555) Python 3.9.10 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-05-03 11:00:55
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Edit Field During Review Cloze ['385888438', 2022-02-22T06:35, '6.11', mod]
    
    ===IDs of active AnkiWeb add-ons===
    385888438

```

**Comment by BlueGreenMagick** [comment]
I think the problem is with the interaction between your note type and the add-on, but I don't have enough information to even make a guess to what might be wrong with it, sorry! 

If you can post your note type here, I can try to figure out what might be wrong it with?

**Comment by omega3** [comment]
https://drive.google.com/file/d/1c-MB0DtXBQLzNIUlfcgjyPNKe0EXCcvT/view?usp=sharing
example collection
click study
and click next to input (type Cloze) black area to the left or to the right and you will see Example_Cloze_Sentence field content.

**Comment by BlueGreenMagick** [comment]
If you disable the add-on, the field doesn't show up either. So I think this is the correct behaviour.
 
You should either cloze something in the field, or remove the `cloze:` and make the field `{{edit:Example_Sentence}}`

**Comment by omega3** [comment]
`{{edit:Example_Sentence}}` This doesn't work at all because when applied it displays cloze all the time like this:
`it displays {{c1::cloze}} all the time like this`

I came up with [this idea](https://forums.ankiweb.net/t/conditional-frame-when-there-is-no-cloze-in-cloze-field/20061).
Your add-on displays blue frame when cloze field is clicked. It could display it before field is clicked and stop displaying when Cloze is made.
I came up with this idea because I have clozes in different places on different note types but Anki always displays this “Please run Tools>Empty Cards” at the bottom. So I can regognize Cloze field in reviewer only by empty space.

Just an idea as an enhancement. 
Other than that thank you for this add-on. It is very helpful.

**Comment by omega3** [comment]
Exactly. This what I do. The first time I see cards in reviewer I make Cloze. This is especially convenient when cards are imported from spreadsheet when no Clozes where made in spreadsheet. Your add-on makes it very convenient. 

Your script works as I wanted when I changed:

```
.mystyle {  
 border: 2px; 
 border-style: hidden;
}
```

and
`
  elem.style.border = "2px groove white"`

So, After I add close border disappear. But this is my personal preference.

Thank you very much.
