### ISSUE TITLE
Problem with copy-pasting in Anki 2.1.52 qt6

### ISSUE THREAD

**Issue by jcznk** [BlueGreenMagick/Edit-Field-During-Review-Cloze#77]
Hello,
if I try to copy and paste a field's contents while they're being displayed during reviewing the following happens

![image](https://user-images.githubusercontent.com/60730312/168416159-4cb9dff9-dc69-437f-8b04-0e9344ecdf53.png)
![image](https://user-images.githubusercontent.com/60730312/168416163-0122d32b-7ad7-4e76-ac82-66594179f43c.png)
![image](https://user-images.githubusercontent.com/60730312/168416320-f6a16fd0-6f8f-4cf1-814a-10048bd701ba.png)
![image](https://user-images.githubusercontent.com/60730312/168416324-31c9ff6a-83dc-4c45-b9e2-598158f0744b.png)

The problems seems to only occur if I copy-paste the displayed content of a field, and in no other case; it also seems to disappear if I toggle "Process pasted content for images and HTML" in the preferences

**Comment by jcznk** [comment]
Actually: a similar problem also appears if I copy the displayed content of a card and paste it to the editor, even if I disable all the addons, so it seems Anki 2.1.52 itself is the culprit

Sorry! 
(And thank you for your great addons)

**Comment by BlueGreenMagick** [comment]
No problem! That's a weird bug and I wouldn't have suspected Anki to be the culprit either.
