### ISSUE TITLE
add remove cloze feature and shortcut

### ISSUE THREAD

**Issue by omega3** [BlueGreenMagick/Edit-Field-During-Review-Cloze#78]
Your add-on is an incredible help when adding Cloze in review mode. But occasionally there is a need for changing what words are on a card with already made Cloze just to make cloze from other word. It would be useful especially when cards are imported from spreadsheet where they were made in a kind of automatic way and require edition.
Could you please consider adding it.

Since [Remove Cloze Button and Hotkey](https://ankiweb.net/shared/info/836994508) hasn’t been updated since 2019-12-22 it would be awesome to be able do it with some shortcut with your add-on. Some regex can be used to achieve this:
`(\{\{c\d::|\}\}) `
- it works in Find and replace option - but would be great to have a keyboard shortcut to execute it when a piece of text is selected. Also "Remove Cloze Button and Hotkey" has regex in its code.

**Comment by BlueGreenMagick** [comment]
I don't think I'll be adding this into the add-on.

That said, if you know JavaScript, you can customize the add-on to add a custom shortcut action. It will only be triggered when you do the shortcut while editing field.

```javascript
EFDRC.registerShortcut("Ctrl + Shift + Alt + R", (event, elem) => {
 // remove {{c1::}} from elem.
}
```

For example, this is the code that wraps cloze on shortcut

```javascript
 function (event, el, altKey = false) {
    let highest = 0
    const val = el.innerHTML
    let m
    const myRe = /\{\{c(\d+)::/g
    while ((m = myRe.exec(val)) !== null) {
      highest = Math.max(highest, m[1])
    }
    if (!altKey) {
      highest += 1
    }
    highest = Math.max(1, highest)
    EFDRC.wrapInternal(document, '{{c' + highest + '::', '}}', false)
    event.preventDefault()
  }
```

**Comment by BlueGreenMagick** [comment]
Added a section to the [FAQ}(https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/blob/master/FAQ.md#how-to-add-a-custom-shortcut-action) about it.
