### ISSUE TITLE
2.1.53 qt6 beta images problem

### ISSUE THREAD

**Issue by jcznk** [BlueGreenMagick/Edit-Field-During-Review-Cloze#79]
Version ⁨2.1.53 (f6ecddef)⁩
Python 3.9.7 Qt 6.3.0 PyQt 6.3.0
Windows 10

Using the addon to paste shrinked images now results in this kind of code being added:
`<!--StartFragment--><img data-editor-shrink="true" src="-" style="max-width: var(--editor-shrink-max-width); max-height: var(--editor-shrink-max-height); width: auto; font-style: normal;"><!--EndFragment--><!--EndFragment-->`

This gives two problems:
1. in the reviewer, the image bypasses any height constraint set by other code (e.g. img max-height in the template is now ignored)
2. in the editor, the pasted image is always shrinked and cannot be expanded

**Comment by BlueGreenMagick** [comment]
Thanks for reporting this! I wouldn't have caught this bug until a lot later. It's going to be such a hassle to support later Anki editor though :(

**Comment by BlueGreenMagick** [comment]
Fixed on [v6.12](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/releases/tag/6.12). I'll probably upload it to ankiweb after testing on my local machine for a while.

**Comment by AnKingMed** [comment]
Maybe @dae would be open to including it in native Anki?

**Comment by BlueGreenMagick** [comment]
I don't think it's possible (or at least very difficult) on Anki-side to control the content that's being copied. 

Exposing `filterHTML` might make things easier though.

**Comment by BlueGreenMagick** [comment]
Uploaded to Ankiweb
