### ISSUE TITLE
Latest update breaks the ctrl+click to edit function

### ISSUE THREAD

**Issue by AnKingMed** [BlueGreenMagick/Edit-Field-During-Review-Cloze#8]
Updated today and I can no longer ctrl+click to edit.  If that option is set to false, I can edit just fine by clicking, but I and many others liked having that option

I'm on a mac (so using Cmd) and 2.1.20. Never had any issues before

**Comment by BlueGreenMagick** [comment]
Sorry for the bug, I think I figured out what the issue is. Could you try editing the addon's global_card.js file and replace all occurence of "ControlLeft" with "OSLeft"?

**Comment by AnKingMed** [comment]
I did that and now when I flip my cards over I'm getting the error "Invalid HTML on card:Reference Error:EFDRC is not defined

**Comment by BlueGreenMagick** [comment]
I suspect you missed a quote mark somewhere. Could you copy paste the code here and try again? https://pastebin.com/wgXy84ZN

**Comment by AnKingMed** [comment]
I just edited my comment there- I broke something, but redownloaded the add-on and tried again and ctrl+click still wasn't working (I only changed two instances to OSLeft at the bottom).  Is there more changes?

**Comment by BlueGreenMagick** [comment]
I was pretty sure it would be OSLeft... Could you try replacing the entire js file with the following:
```
window.addEventListener('keydown',function(event){
        document.body.innerHTML = event.code
})
```
Then press cmd, and copy paste what is written on the card?

**Comment by AnKingMed** [comment]
"MetaLeft" is what shows up

**Comment by BlueGreenMagick** [comment]
I pushed the update to ankiweb. Could you try updating the addon and see if the issue is fixed?

**Comment by AnKingMed** [comment]
Working now! Thanks for the extremely quick fix
