### ISSUE TITLE
Conflict with the Chinese script 

### ISSUE THREAD

**Issue by chicuong122003** [BlueGreenMagick/Edit-Field-During-Review-Cloze#86]
The version before 27/June was working ok when I don't apply this add on upon Chinese decks which have this type of script (chinese stroke animation) , but after I update the 27/June version, the add on conflicts with the script for chinese strokes although I didn't change anything. 

 Cards won't display strokes when I enable your add on.
<img width="525" alt="Screen Shot 2022-06-28 at 10 18 37" src="https://user-images.githubusercontent.com/108315663/176084718-12f53956-1d20-46b5-bdbc-2155ba44cfda.png">

Strokes are normally displayed when I disabled your add on. In the previous version, when I enable your add on, cards would still display strokes on condition that I don't apply your add on upon cards that have the script for chinese strokes. 
<img width="508" alt="Screen Shot 2022-06-28 at 10 18 15" src="https://user-images.githubusercontent.com/108315663/176085340-a095d38c-d66e-4d9e-b60a-fbbcef6e6c68.png">
<img width="665" alt="Screen Shot 2022-06-28 at 10 17 56" src="https://user-images.githubusercontent.com/108315663/176085446-3403f92d-fd0c-4131-8e27-5394261f741f.png">

**Comment by BlueGreenMagick** [comment]
Does your script have a closing tag? Because in the picture it seems like it doesn't. JavaScript should be wrapped in `<script>...</script>`

If so, can you use the [Ankiwebview Inspector](https://ankiweb.net/shared/info/31746032) and see what errors are written in the console tab?

**Comment by chicuong122003** [comment]
Thank you for replying my report. I'm surpised by your friendliness as I thought my report would never be noticed :) 

The script for chinese stroke is taken from the Internet. I have tried to wrap it in <script>...</script> as you told but it didn't work. Besides, I'm not a coder so I don't know how to use the [Ankiwebview Inspector].

<div` id="target"></div>
<script type="text/javascript">
	var characters = "{{Character}}".split("")
	var js = document.createElement("script");
	js.type = "text/javascript";
	js.src = "https://cdn.jsdelivr.net/npm/hanzi-writer@2.2/dist/hanzi-writer.min.js";
	js.onload = function() {
		for (x of characters) {
			var writer = HanziWriter.create('target', x, {
				width: 150,
				height: 150,
				padding: 5,   
				showOutline: true,
				strokeAnimationSpeed: 2, 
				delayBetweenStrokes: 200, // milliseconds
				radicalColor: '#F32424' // salmon
			});
			writer.loopCharacterAnimation();
		};
	};
	document.body.appendChild(js); 

[https://drive.google.com/file/d/1rwS-xZpL3XH0YQ04aWSBLCE6BKZUiHIa/view?usp=sharing](url)


Here is the script and a deck of mine that contain the script. Could you take a look at it please ✌️ .
Thank you in advance. 
Admire your talent and your working manner.

**Comment by BlueGreenMagick** [comment]
The problem was indeed the closing script tag. Add this line to the end of the note type Back, and it should work! (As long as you don't make the 'Character' field editable)
```html
</script>
```

Thanks for the detailed bug report!
