### ISSUE TITLE
 Request to change the format of cloze

### ISSUE THREAD

**Issue by yasm2** [BlueGreenMagick/Edit-Field-During-Review-Cloze#88]
Above all, thank you so much for making this add-on.
This is really the best add-on.
I am very satisfied after using this add-on.
That's why I'd like to request some feature additions

Anki provides basic cloze.
And this add-on is really convenient because it allows you to easily create a basic cloze through a shortcut.
However, the basic cloze has several limitations.
That's why I'm using a different form of cloze
Closet For Anki (https://ankiweb.net/shared/info/272311064)

This Closet For Anki can use a variety of clozes such as images, text, and blur at the same time.

But unfortunately it cannot be used with Edit-Field-During-Review-Cloze.

The request is simple.
**{{c1::hidden closed text }} => [[cl1::hidden closed text]]**

In this way, I want to be able to change the format of cloze through the environment setting.

If you can change the configuration of the format of this cloze
It can be used together with several other cloze extensions.

**Comment by BlueGreenMagick** [comment]
You can register a custom action that does this. Put the following code into the front side of all your note types.

```html
<script>
if (!clozeClRun) {
clozeClRun = true

const wrapClozeCl = function (event, el, altKey) {
    let highest = 0
    const val = el.innerHTML
    let m
    const myRe = /\[\[cl(\d+)::/g
    while ((m = myRe.exec(val)) !== null) {
      highest = Math.max(highest, m[1])
    }
    if (!altKey) {
      highest += 1
    }
    highest = Math.max(1, highest)
    EFDRC.wrapInternal(el, '[[cl' + highest + '::', ']]', false)
    event.preventDefault()
  }
EFDRC.registerShortcut("Ctrl+Shift+C", (event, elem) => {
wrapClozeCl(event, elem, false);
})
EFDRC.registerShortcut("Ctrl+Shift+Alt+C", (event, elem) => {
wrapClozeCl(event, elem, true);
})
}
</script>
```
