### ISSUE TITLE
A crown covers my cloze deletion, GET IT OFF PLZ HELP :(

### ISSUE THREAD

**Issue by FireWizard000** [BlueGreenMagick/Edit-Field-During-Review-Cloze#90]
![Screenshot (1)](https://user-images.githubusercontent.com/112772582/188280021-f1bb03a6-0135-40a0-8930-0da44baca516.png)

**Comment by BlueGreenMagick** [comment]
This looks like Anking notetype problm, not this add-on problm.

That said, I think you can turn it off by making 'One by one' field blank
