### ISSUE TITLE
Cannot use two modifiers (Anki V 2.1.58)

### ISSUE THREAD

**Issue by rccalma** [BlueGreenMagick/Edit-Field-During-Review-Cloze#93]
Hi,

I noticed I cannot use two modifiers anymore. For example, if I use "Ctrl + CMD + C" for JustifyCenter, the action JustifyCenter will be provoked with CMD + C or Ctrl + C but not CTRL + CMD + C.
<img width="566" alt="Screenshot 2023-02-20 at 12 05 47 PM" src="https://user-images.githubusercontent.com/88975900/220175348-464a62e6-f838-4c0f-b410-717f42ea6640.png">

**Comment by BlueGreenMagick** [comment]
The add-on does not support `Cmd`. You have to use `Ctrl` for both `cmd` and `ctrl` keys on mac.

I can't fix this because that'd break for everyone who are using `Ctrl` to detect `cmd` keys.
