### ISSUE TITLE
Esc no longer works to quit editing (2.1.60qt6)

### ISSUE THREAD

**Issue by Neosaurus** [BlueGreenMagick/Edit-Field-During-Review-Cloze#94]
The below checklist isn't manditory, but suggested before creating an issue.
- [X] I've updated this add-on to the latest version
- [ ] I've tried disabling all other add-ons except this one.

**Describe the bug**
What is the bug, and what behaviour did you expect instead?
Esc no longer works to stop editing

**To Reproduce**
1. Edit cloze as normal
2. Esc no longer works to stop editing, you must click

**Debug Info**
In the toolbar, go to `Help > About...`. In the About window, click the `Copy Debug Info` button at the bottom beside an 'OK' button. Please paste the contents below.
    
    Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
    Platform: macOS-13.2.1-arm64-arm-64bit
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-03-02 10:46:51
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Table ['1237621971', 2022-12-21T11:20, 'None', mod]
    Additional Card Fields Fork for 21 ['744725736', 2022-10-23T11:10, 'None', '']
    Advanced Browser ['874215009', 2022-09-27T01:28, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2023-01-31T19:52, 'None', mod]
    AnKing Note Types Easy Customization ['952691989', 2023-02-22T20:14, 'None', mod]
    Anki Simulator ['817108664', 2021-08-07T20:24, 'None', '']
    AnkiConnect ['2055492159', 2022-09-19T01:11, 'None', mod]
    AnkiHub ['1322529746', 2023-02-19T08:46, 'None', '']
    Automatic Dark Night Mode ['446355629', 2021-05-15T19:22, 'None', '']
    Automatically rebuild filtered deck ['1997713323', 2021-07-18T16:18, 'None', mod]
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2023-02-25T04:32, 'None', '']
    Batch Editing ['291119185', 2019-06-02T19:47, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T22:25, 'None', mod]
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T22:11, 'None', mod]
    Bury Cousins related cards that arent siblings ['1072815885', 2021-07-20T02:23, 'None', '']
    Card Info During Review ['2179254157', 2022-11-03T01:34, 'None', '']
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T16:06, 'None', '']
    Countdown To Events and Exams ['1143540799', 2022-06-27T12:50, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T10:12, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2022-06-27T10:48, '6.13', mod]
    Exam Notifier ['exam_notifier', 2021-09-02T13:35, 'None', '']
    Export Single Tag For Sharing ['960563361', 2022-04-10T22:30, 'None', '']
    FSRS4Anki Helper ['759844606', 2023-03-01T05:36, 'None', '']
    Fastbar- with nightmode support ['46611790', 2023-02-17T23:18, 'None', mod]
    Field AutoComplete ['511710206', 2023-02-26T00:27, 'None', mod]
    Find and Replace in Card templatesNotetypesHTML ['992153575', 2021-09-17T07:34, 'None', '']
    Google Translate ['1536291224', 2022-11-13T00:00, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-09-22T14:37, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T18:45, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T13:05, 'None', '']
    New Card Counter ['new_card_counter', 2021-06-09T16:48, 'None', mod]
    Remove Cloze Button and Hotkey ['1966460736', 2022-05-21T11:29, 'None', mod]
    Removes Empty Note Types for 21 ['530953383', 2019-06-12T15:11, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
    Search and Replace Tags ['138501288', 2017-08-29T19:58, 'None', '']
    Show total time spent in main screen ['1238121460', 2020-07-19T09:36, 'None', '']
    Shrink Image Size In Editor ['1633333766', 2022-10-21T10:23, 'None', '']
    Special Fields ['1102281552', 2022-11-22T01:49, 'None', mod]
    Straight Reward ['957961234', 2022-12-12T13:49, 'None', '']
    Switch Note Type Hotkey ['565948788', 2021-10-04T04:46, 'None', mod]
    True Retention ['613684242', 2017-11-19T20:43, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2021-12-05T20:28, 'None', '']
    right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable ['850294128', 2021-12-06T15:00, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1052724801 1072815885 1102281552 1136455830 1143540799 1237621971 1238121460 1322529746 1374772155 138501288 1436550454 1536291224 1556734708 1633333766 1771074083 1966460736 1997713323 2055492159 2179254157 24411424 291119185 295889520 385888438 446355629 46611790 511710206 530953383 561945101 565948788 594329229 613684242 744725736 759844606 817108664 831846358 850294128 874215009 952691989 957961234 960563361 992153575
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['motivanki to modify', 0, 'None', '']
    Collapsible Fields ['1896168623', 2021-08-28T22:45, 'None', '']
    Motivanki ['663438166', 2022-06-23T16:38, 'None', '']
    Opening the same window multiple time ['354407385', 2020-05-16T01:59, 'None', '']
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-19T22:32, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T11:24, 'None', '']
    Symbols As You Type ['2040501954', 2022-06-08T05:09, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-07T02:31, 'None', '']
    The KING of Button Add-ons ['374005964', 2023-02-17T23:21, 'None', mod]
    The KING of Study Timers ['907028815', 2022-04-20T19:14, 'None', '']

**Comment by DoubleUltera** [comment]
For the moment, I use **Tab** to quit edit mode. **Esc** would definitely be appropriate though.

Cheers!

**Comment by BlueGreenMagick** [comment]
Fixed! The fix will be included in next release
