### ISSUE TITLE
Stopped working on 2.1.64 Qt6

### ISSUE THREAD

**Issue by MightyBooman** [BlueGreenMagick/Edit-Field-During-Review-Cloze#98]
The below checklist isn't manditory, but suggested before creating an issue.
- [ x] I've updated this add-on to the latest version
- [ ] I've tried disabling all other add-ons except this one.

**Describe the bug**
The add-on stopped working for me after updating to 2.1.64 qt6. I can no longer edit while reviewing with 'Cmd+left click' on a MacBook.

**Comment by BlueGreenMagick** [comment]
It's working fine on my macbook. (2.1.64 qt6) Can you check that you marked the note type field editable? You can do that in `add-on config > Fields`

**Comment by MightyBooman** [comment]
All the notetypes were selected. I checked and unchecked the cmd+click option. I also had to use new shortcuts using cmd+alt+S click, which seemed to work. False alarm

**Comment by BlueGreenMagick** [comment]
To clarify, it's working fine for you now?

**Comment by MightyBooman** [comment]
I just pushed the update this morning (7/12) and it is now working perfectly as it did before I updated Anki to 2.1.64. I'm not sure why I was having a difficult time before. I love this addon - it sucked not having it. Thanks for your help
