### ISSUE TITLE
Hotkey for CMD?

### ISSUE THREAD

**Issue by rccalma** [BlueGreenMagick/Edit-Field-During-Review-Cloze#99]
The below checklist isn't manditory, but suggested before creating an issue.
- [x] I've updated this add-on to the latest version
- [ ] I've tried disabling all other add-ons except this one.

Hi,

When I am configuring this addon and formatting it, what is the name of the command key? Ctrk is control, shift is shift, alt is alt/option; what is command? I want to set the indent hotkey to cmd + ].

Thanks! Your addon is amazing.

**Comment by BlueGreenMagick** [comment]
`Ctrl` works for both Cmd and Ctrl on mac. There isn't a separate command for `Cmd` key.
